---
- name: Install dhcp server on Ubuntu
  apt:
    name: isc-dhcp-server
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install dhcp server on CentOS
  yum:
    name: dhcp
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

