---
# tasks file for Mariadb
- name: install mariadb server package (Ubuntu)
  tags: ubuntu, db, mariadb
  apt:
   name: mariadb-server
   state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb server package (CentOS)
  tags: centos, db, mariadb
  yum:
   name: mariadb-server
   state: latest
  when: ansible_distribution == "CentOS"
